name: FuelForecaster
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py312ha2b695f_0
  - brotli-python=1.0.9=py312h6d0c2b6_9
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.2.25=hecd8cb5_0
  - certifi=2025.1.31=py312hecd8cb5_0
  - expat=2.6.4=h6d0c2b6_0
  - ipywidgets=8.1.5=py312hecd8cb5_0
  - jedi=0.19.2=py312hecd8cb5_0
  - joblib=1.4.2=py312hecd8cb5_0
  - jupyterlab_widgets=3.0.13=py312hecd8cb5_0
  - libcxx=14.0.6=h9765a3e_0
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libopenblas=0.3.21=h54e7dc3_0
  - libxgboost=2.1.1=hab2016f_0
  - llvm-openmp=14.0.6=h0dcd299_0
  - ncurses=6.4=hcec6c5f_0
  - numexpr=2.10.1=py312hc59c7be_0
  - numpy=2.2.2=py312h255ab90_0
  - numpy-base=2.2.2=py312h12d8432_0
  - openssl=3.0.16=h184c1cd_0
  - packaging=24.2=py312hecd8cb5_0
  - pandas=2.2.3=py312h6d0c2b6_0
  - parso=0.8.4=py312hecd8cb5_0
  - pip=25.0=py312hecd8cb5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=2.1.1=py312hecd8cb5_0
  - pysocks=1.7.1=py312hecd8cb5_0
  - python=3.12.9=hcd54a6c_0
  - python-dateutil=2.9.0post0=py312hecd8cb5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py312hecd8cb5_0
  - readline=8.2=hca72f7f_0
  - requests=2.32.3=py312hecd8cb5_1
  - scikit-learn=1.6.1=py312h6d0c2b6_0
  - scipy=1.15.1=py312hff39f35_0
  - setuptools=72.1.0=py312hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h6c40b1e_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py312h8e4b320_0
  - tk=8.6.14=h4d00af3_0
  - tqdm=4.67.1=py312h8e4b320_0
  - traitlets=5.14.3=py312hecd8cb5_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py312hecd8cb5_0
  - wheel=0.45.1=py312hecd8cb5_0
  - widgetsnbextension=4.0.13=py312hecd8cb5_0
  - xgboost=2.1.1=py312hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - anyio==4.9.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - comm==0.2.2
      - cramjam==2.9.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - defusedxml==0.7.1
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fastparquet==2024.11.0
      - fqdn==1.5.1
      - frozendict==2.4.6
      - fsspec==2025.3.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - isoduration==20.11.0
      - jinja2==3.1.6
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kagglehub==0.3.10
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - multitasking==0.0.11
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - peewee==3.17.9
      - pexpect==4.9.0
      - platformdirs==4.3.7
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pycparser==2.22
      - pygments==2.19.1
      - python-json-logger==3.3.0
      - pyyaml==6.0.2
      - pyzmq==26.3.0
      - referencing==0.36.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.24.0
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tornado==6.4.2
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.0
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - yfinance==0.2.55
prefix: /opt/anaconda3/envs/FuelForecaster
